export const procedureOptions: string[] = [
  'Profilaxia',
  'Restauração',
  'Exodontia',
  'Endodontia',
  'Radiografia',
  'Clareamento gel',
  'Clareamento à laser',
  'Placa de bruxismo',
  'Colagem',
  'Fluor',
  'Placa',
  'Provisório',
  'Prótese',
  'Raio X',
  'Remoção de sutura',
  'Bisnaga de clareamento',
  'Cirurgia',
  'Vários procedimentos',
  'Emergência',
  'Selante (por unidade)',
  'Pino fibra de vidro para restauração',
  'Pino metálico Reforpost para restauração',
  'Faceta',
  'Coroa metalo-cerâmica',
  'Coroa cerâmica pura',
  'Coroa de acrílico provisório',
  'Coroa de acrílico prensado',
  'Laminado cerâmico por dente',
  'Núcleo',
  'Implante',
  'Pino',
  'Ortodontia',
  'Contenção',
  'Estética'
];